### ISSUE TITLE
Does not work on fedora

### ISSUE THREAD

**Issue by chadmf** [ansible-collections/osbuild.composer#14]
does not work for fedora

##### SUMMARY
to fix need to add something like this to the server role:

```
- name: RHEL9 Centos 9 and Fedora specific setup
  block:
    - name: install toml
      ansible.builtin.dnf:
        state: latest
        name:
          - python3-toml
  when:
    - ansible_distribution in ['RedHat', 'CentOS', 'Fedora']
    - ansible_distribution_major_version|int >= 9
```

##### ISSUE TYPE
- Bug Report
